//AIRING
export const API_REQUEST = 'API_REQUEST'
export const API_SUCCESS = 'API_SUCCESS'
export const API_FAILURE = 'API_FAILURE'
export const API_LIST_END = 'API_LIST_END'
export const FILTER_ANIME_LIST = 'FILTER_ANIME_LIST'

//COMPLETE
export const COMPLETE_API_REQUEST = 'COMPLETE_API_REQUEST'
export const COMPLETE_API_SUCCESS = 'COMPLETE_API_SUCCESS'
export const COMPLETE_API_FAILURE = 'COMPLETE_API_FAILURE'
export const COMPLETE_API_LIST_END = 'COMPLETE_API_LIST_END'
export const COMPLETE_FILTER_ANIME_LIST = 'COMPLETE_FILTER_ANIME_LIST'

//UPCOMING
export const UPCOMING_API_REQUEST = 'UPCOMING_API_REQUEST'
export const UPCOMING_API_SUCCESS = 'UPCOMING_API_SUCCESS'
export const UPCOMING_API_FAILURE = 'UPCOMING_API_FAILURE'
export const UPCOMING_API_LIST_END = 'UPCOMING_API_LIST_END'
export const UPCOMING_FILTER_ANIME_LIST = 'UPCOMING_FILTER_ANIME_LIST'

//FAVOURITE
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES'
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES'
export const FILTER_FROM_FAVOURITES = 'FILTER_FROM_FAVOURITES'